writeln( "0 is ", (true and 0) )
writeln( "1 is ", (true and 1) )
writeln( "-1 is ", (true and -1) )
writeln( "Empty string is ", (true and "") )
writeln( "nil is ", (true and nil) )
writeln( "true is ", (true) )
writeln( "false is ", (false) )